### PR TITLE
Add automated accessibility testing to Cypress checks

### PR DESCRIPTION
**Pull request by jeff-horton-ho-sas**
Add `axe-core` and `cypress-axe` to provide automated tests for (some) accessibility issues in site pages. 

Fix any accessibility issues detected.

### CODE REVIEW

**Comment by jeff-horton-ho-sas** [comment]
Initial work to add testing. Some of the detected issues can be fixed by us, but some will need upstream changes to x-gov-11ty-plugin layouts. Also needs some work to surface to contributors what the actual issues are as the current test failures look like:
```
AssertionError: 2 accessibility violations were detected: expected 2 to equal 0
```

**Comment by jeff-horton-ho-sas** [comment]
Issues causing test failures:

- [x] #126 Unexepected empty lists - site root has been moved to `/docs` - macro paths needed updating
- [x] #130 Phase banner not in landmark region - ignored and added to technical decision log
- [ ] #131 Product page banner not in landmark region - to be resolved upstream before this is merged
- [x] #133 Breadcrumbs now wrapped in `nav`

**Comment by edhamiltonHO** [comment]
Going to need to do another pass of standards principles and pattern .md files, immediately before merge, to make sure any new ones have the below change applied:

```
- {% import "_includes/macros/tags.njk" as pageTag %}
+ {% import "macros/tags.njk" as pageTag %}
```

**Review by edhamiltonHO — APPROVED** [review]
Looks good to me

**Review by keithkennedyHO — APPROVED** [review]

**Pull request merged**
